# Default values for p1-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enableRedis: false
enableMongo: false
enableCertIssuer: false

ingress:
  hostname: auth.tst.protocol.one
  path: /

certIssuer:
  email: admin@protocol.one

frontend:
  name: nginx
  role: frontend  
  image: "nginx:1.15.4"
  imageTag: 1.15.4
  port: 80
  replicas: 1
  service: 
    type: ClusterIP
    port: 8080
    protocol: TCP
  configMap: 
    mountPath: /etc/nginx/conf.d/

backend:
  name: fpm
  role: backend
  image: "p1hub/auth.protocol.one"
  imageTag: latest
  replicas: 1
  port: 9000
  service:
    type: ClusterIP
    port: 9000
    protocol: TCP
    
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
